NFS_CORE_PARAM {
    NFS_Protocols = 4;
    Bind_addr = 0.0.0.0;
    NFS_Port = 2049;
}

NFSV4 {
    Grace_Period = 0;
}

EXPORT {
    Export_Id = 1;
    Path = /export;
    Pseudo = /export;
    Access_Type = RW;
    Squash = No_Root_Squash;
    SecType = sys;
    Protocols = 4;
    Transports = TCP;

    FSAL {
        Name = MEM;
    }
}

LOG {
    Default_Log_Level = EVENT;

    COMPONENTS {
        NFS_V4 = DEBUG;
        STATE = DEBUG;
        EXPORT = DEBUG;
        FSAL = DEBUG;
    }
}
